### ISSUE TITLE
install WRS

### ISSUE THREAD

**Issue by ivan-paleo** [NicolasStefaniak/easieR#10]
Hi Nicolas,

I couldn't find a way to install the package WRS on R4.2.2 for Win10:
`install_github("nicebread/WRS")` returns an "HTTP error 404 not found"
`ez.install()` gives a warning that "package ‘WRS’ is not available for this version of R".

Is it critical? If yes, maybe you can update your installation instructions.
Also it seems Rtools is needed, but this is not mentioned in your installation instructions

Best,
Ivan

**Comment by NicolasStefaniak** [comment]
Hi Ivan,
the package is not critical. Nevertheless, you can install it by using the following command line:
`library("devtools")`
`install_github("nicebread/WRS", subdir="pkg")`

I have just tried, the link still works.
The warning of `ez.install` is expected due to the fact that WRS is not an official R package but is only available on github. 
I am going to update `ez.install` to avoid the warning. 
Tell me if it worked. 
Best. 
Nicolas

**Comment by ivan-paleo** [comment]
`install_github("nicebread/WRS", subdir="pkg")`
Skipping install of 'WRS' from a github remote, the SHA1 (29f2768b) has not changed since last install.
  Use `force = TRUE` to force installation

I guess I should force the installation? I never had this message so I'm not sure...

**Comment by NicolasStefaniak** [comment]
It seems that WRS has already been installed. 
The function `ez.install` run the correct command line. You do not have anything to do anymore. 
Installation is completed.

**Comment by ivan-paleo** [comment]
So it seems that `ez.install()` does its job but the message got me confused. That's great, thanks!
