### ISSUE TITLE
Error installing easieR

### ISSUE THREAD

**Issue by P1AME** [NicolasStefaniak/easieR#9]
Can't download easieR because "QuantPsyc" is not available.

**Comment by NicolasStefaniak** [comment]
Dear P1AME, 
thank you for the message. Indeed, QuantPsyc is not available anymore since last week. I need to suppress the dependency. 
For the moment, a possible solution is to manually install the last version of QuantPsyc that is available. 
You can find it here: https://cran.r-project.org/src/contrib/Archive/QuantPsyc/
Best,
Nicolas

**Comment by NicolasStefaniak** [comment]
Dear P1AME,
I have corrected the dependency. You should be able to install easieR now. 
Let me know.
Best
